/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  theme: {
    fontSize: {
      'xs': ['0.75rem', { lineHeight: '1.125rem' }],
      'sm': ['0.875rem', { lineHeight: '1.375rem' }],
      'base': ['0.9375rem', { lineHeight: '1.5rem' }],
      'lg': ['1.0625rem', { lineHeight: '1.625rem' }],
      'xl': ['1.1875rem', { lineHeight: '1.75rem' }],
      '2xl': ['1.375rem', { lineHeight: '1.875rem' }],
      '3xl': ['1.625rem', { lineHeight: '2.125rem' }],
      '4xl': ['2rem', { lineHeight: '2.5rem' }],
      '5xl': ['2.5rem', { lineHeight: '2.75rem' }],
    },
    extend: {
      colors: {
        brand: {
          primary: '#00AFCE',
          'primary-hover': '#009AA8',
          'primary-active': '#008494',
          'primary-light': '#E5F8FA',
          dark: '#1d1d1d',
          'dark-hover': '#0a0a0a',
          light: '#E5F2F3',
          'light-hover': '#D5E8E9',
          accent: '#F59E0B',
          'accent-light': '#FEF3C7',
          'accent-dark': '#D97706',
        },
        dark: {
          bg: '#141414',
          'bg-side': '#0C0C0C',
          card: '#1E1E1E',
          'card-hover': '#262626',
          line: '#2E2E2E',
          'line-hover': '#3A3A3A',
          tuerkis: '#00B3C7',
          'tuerkis-hover': '#1AD0E4',
          'tuerkis-dark': '#0B1E22',
          gelb: '#F9EE80',
          tx: '#FFFFFF',
          'tx-2': '#A6A6A6',
          'tx-3': '#6E6E6E',
          'st-offen': '#6E6E6E',
          'st-termin': '#00B3C7',
          'st-teil': '#F9EE80',
          'st-quiz': '#FF8A3D',
          'st-done': '#3DD68C',
        },
        ui: {
          success: '#22C55E',
          'success-light': '#DCFCE7',
          'success-dark': '#16A34A',
          warning: '#F59E0B',
          'warning-light': '#FEF3C7',
          'warning-dark': '#D97706',
          error: '#EF4444',
          'error-light': '#FEE2E2',
          'error-dark': '#DC2626',
          info: '#3B82F6',
          'info-light': '#DBEAFE',
          'info-dark': '#2563EB',
        },
        surface: {
          50: '#FAFBFC',
          100: '#F4F5F7',
          200: '#E5E7EB',
          300: '#D1D5DB',
          400: '#9CA3AF',
          500: '#6B7280',
          600: '#4B5563',
          700: '#374151',
          800: '#1F2937',
          900: '#111827',
        }
      },
      fontFamily: {
        sans: [
          'Inter',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        display: [
          'Plus Jakarta Sans',
          'Inter',
          'system-ui',
          'sans-serif',
        ],
        mono: [
          'JetBrains Mono',
          'Fira Code',
          'SF Mono',
          'Consolas',
          'Liberation Mono',
          'monospace',
        ],
        'dark-display': [
          'Mulish',
          'Arial Black',
          'sans-serif',
        ],
        'dark-body': [
          'Lato',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      spacing: {
        '0.5': '0.125rem',
        '1.5': '0.375rem',
        '2.5': '0.625rem',
        '3.5': '0.875rem',
        '4.5': '1.125rem',
      },
      borderRadius: {
        'sm': '0.375rem',
        'DEFAULT': '0.5rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        'dark': '14px',
      },
      boxShadow: {
        'tool': '0 1px 3px rgb(0 0 0 / 0.04), 0 4px 12px rgb(0 0 0 / 0.06)',
        'tool-md': '0 2px 8px rgb(0 0 0 / 0.06), 0 8px 24px rgb(0 0 0 / 0.08)',
        'tool-lg': '0 4px 16px rgb(0 0 0 / 0.08), 0 16px 48px rgb(0 0 0 / 0.12)',
        'dropdown': '0 8px 24px rgb(0 0 0 / 0.12), 0 2px 8px rgb(0 0 0 / 0.06)',
        'modal': '0 24px 48px -12px rgb(0 0 0 / 0.18), 0 8px 16px -8px rgb(0 0 0 / 0.1)',
        'card-hover': '0 8px 30px rgb(0 0 0 / 0.1), 0 2px 8px rgb(0 0 0 / 0.05)',
      },
      transitionDuration: {
        '150': '150ms',
        '200': '200ms',
      },
      ringColor: {
        DEFAULT: '#00AFCE',
      },
      ringOffsetWidth: {
        DEFAULT: '2px',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'fade-out': 'fadeOut 0.2s ease-in',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.2s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'skeleton': 'skeleton 1.5s ease-in-out infinite',
        'progress-fill': 'progressFill 0.8s ease-out forwards',
        'card-enter': 'cardEnter 0.4s ease-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        skeleton: {
          '0%': { backgroundPosition: '-200px 0' },
          '100%': { backgroundPosition: 'calc(200px + 100%) 0' },
        },
        progressFill: {
          '0%': { width: '0%' },
          '100%': { width: 'var(--progress-width)' },
        },
        cardEnter: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}


